spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:C:\Users\10598925708\Desktop\WorkSpace\eventh2
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
